site_name: Mosaic
theme:
  name: readthedocs
  locale: en
  include_sidebar: true
  highlightjs: true
  logo: img/favicon-96x96.png
  custom_dir: custom_theme/
  titles_only: true
  navigation_depth: 3
extra_css:
  - style.css
use_directory_urls: false
nav:
  - Mosaic Introduction: index.md
  - Status and Development: status.md
  - Rationale: rationale.md
  - Mosaic Core:
    - Identity:
      - Cryptography: cryptography.md
      - Identity: identity.md
      - Bootstrap: bootstrap.md
    - Record Type:
      - Timestamps: timestamps.md
      - Record Format: record.md
      - Human Readable Content: human_readable_content.md
      - Core Tags: core_tags.md
    - References: reference.md
    - Core Records:
      - Key Schedule Record: keyschedule.md
      - Profile Record: profile.md
    - Protocol:
      - Filter: filter.md
      - Core Protocol: protocol.md
    - Registries:
      - Tag Type Registry: tag_types.md
      - Record Kind Registry: kinds.md
  - Mosaic Accessory:
    - Human Encodings: human_encodings.md
  - Mosaic Transport:
    - WebSockets: websockets.md
    - WebTransport: webtransport.md
  - Extensions:
    - Sync Protocol Extension: sync_protocol_extension.md
  - Applications:
    - Mosaic Social media:
      - Microblogging: microblog.md
      - Blog: blog.md
      - Reply Comment: reply_comment.md
      - Chat: chat.md