site_name: Mosaic
theme:
  name: readthedocs
  locale: en
  include_sidebar: true
  highlightjs: true
  logo: img/favicon-96x96.png
  custom_dir: custom_theme/
  titles_only: true
extra_css:
  - style.css
nav:
  - Mosaic Introduction: index.md
  - Status and Development: status.md
  - Mosaic Core:
    - Identity:
      - Cryptography: cryptography.md
      - Identity: identity.md
      - Bootstrap: bootstrap.md
    - Timestamps: timestamps.md
    - Record: record.md
    - Reference: reference.md
    - Tag Type Registry: tag_types.md
    - Record Kind Registry: kinds.md
    - Core Records:
      - Key Schedule: keyschedule.md
      - Profile: profile.md
    - Core Tags: core_tags.md
    - Core Protocol:
      - Protocol: protocol.md
      - Filter: filter.md
  - Mosaic Transport:
    - WebSockets: websockets.md
    - WebTransport: webtransport.md
    - REST: rest.md
  - Extensions:
    - Sync Protocol Extension: sync_protocol_extension.md
  - Applications:
    - Mosaic Social media:
      - Microblogging: microblog.md
      - Blog: blog.md
      - Reply Comment: reply_comment.md
      - Chat: chat.md